CREATE TABLE BOOKS (
    BookID INTEGER GENERATED BY DEFAULT AS IDENTITY,
    Title VARCHAR (40) NOT NULL,
    Author VARCHAR (40) NOT NULL,
    Genre VARCHAR (40) NOT NULL,
    Price DECIMAL (5, 2) NOT NULL,
    CONSTRAINT PK_BOOKS PRIMARY KEY (BookID)
);

INSERT INTO BOOKS (BookID, Title, Author, Genre, Price) VALUES (1, 'Things Fall Apart', 'Chinua Achebe', 'Historical', 10.00);
INSERT INTO BOOKS (BookID, Title, Author, Genre, Price) VALUES (2, 'Slaughterhouse-Five', 'Kurt Vonnegut', 'Satire', 6.00);
INSERT INTO BOOKS (BookID, Title, Author,  Genre, Price) VALUES (3, 'Cat''s Cradle', 'Kurt Vonnegut', 'Science Fiction', 9.00);
INSERT INTO BOOKS (BookID, Title, Author,  Genre, Price) VALUES (4, 'Breakfast of Champions', 'Kurt Vonnegut', 'Satire', 11.00);
INSERT INTO BOOKS (BookID, Title, Author,  Genre, Price) VALUES (5, 'Ender''s Game', 'Orson Scott Card', 'Science Fiction', 7.00);
INSERT INTO BOOKS (BookID, Title, Author,  Genre, Price) VALUES (6, 'Speaker for the Dead', 'Orson Scott Card', 'Science Fiction', 8.00);
INSERT INTO BOOKS (BookID, Title, Author,  Genre, Price) VALUES (7, 'The Fellowship of the Ring', 'J. R. R. Tolkien', 'Fantasy', 18.00);
INSERT INTO BOOKS (BookID, Title, Author,  Genre, Price) VALUES (8, 'The Two Towers', 'J. R. R. Tolkien', 'Fantasy', 18.00);
INSERT INTO BOOKS (BookID, Title, Author,  Genre, Price) VALUES (9, 'The Return of the King', 'J. R. R. Tolkien', 'Fantasy', 18.00);
INSERT INTO BOOKS (BookID, Title, Author,  Genre, Price) VALUES (10, 'The Hitchhiker''s Guide to the Galaxy', 'Douglas Adams', 'Science Fiction', 7.00);
INSERT INTO BOOKS (BookID, Title, Author,  Genre, Price) VALUES (11, 'A Game of Thrones', 'George R. R. Martin', 'Fantasy', 13.00);

--DROP TABLE BOOKS;



-- Select queries

SELECT Genre, UPPER(Title) AS "Title", UPPER(Author) AS "Author", price AS "Price"
FROM BOOKS
ORDER BY Genre, Title; -- get all books and display in order of Genre, then by Title

SELECT DISTINCT Genre, -- only use each Genre once
FIRST_VALUE(Title) OVER (PARTITION BY Genre ORDER BY Title) AS "First in Genre", -- get first book of each Genre
LAST_VALUE(Title) OVER (PARTITION BY Genre) AS "Last in Genre" -- get last book of each genre
FROM BOOKS
ORDER BY Genre; -- display results in order of Genre